### ISSUE TITLE
Platform error climate.climate_group - cannot import name 'GroupEntity' from 'custom_components.climate_group'

### ISSUE THREAD

**Issue by sebaurel** [daenny/climate_group#58]
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Interface utilisateur : 20221108.0 - latest

climate_group 1.0.0-rc1

Hello, since i update to 1.0.0-rc1, i can't restart Homme assistant because i have a config error :

```
2022-11-15 08:43:12.106 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-15 08:43:34.138 ERROR (MainThread) [homeassistant.config] Platform error: climate
File "/config/custom_components/climate_group/climate.py", line 55, in <module>
ImportError: cannot import name 'GroupEntity' from 'custom_components.climate_group' (/config/custom_components/climate_group/__init__.py)
2022-11-15 10:20:45.723 ERROR (MainThread) [homeassistant.components.hassio] The system cannot restart because the configuration is not valid: Platform error climate.climate_group - cannot import name 'GroupEntity' from 'custom_components.climate_group' (/config/custom_components/climate_group/__init__.py)
2022-11-15 10:20:45.751 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547431646064] The system cannot restart because the configuration is not valid: Platform error climate.climate_group - cannot import name 'GroupEntity' from 'custom_components.climate_group' (/config/custom_components/climate_group/__init__.py) 
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.climate_group - cannot import name 'GroupEntity' from 'custom_components.climate_group' (/config/custom_components/climate_group/__init__.py)
```

my configuration :
```
climate:
  - platform: climate_group
    name: 'Thermostat général'
    temperature_unit: C  # default to celsius, 'C' or 'F'
    entities:
    - climate.radiateur_salon
    - climate.radiateur_cuisine
```
 
Thanks a lot for your work.

**Comment by daenny** [comment]
Can you try again?
https://github.com/daenny/climate_group/releases/tag/1.0.0-rc2

**Comment by sebaurel** [comment]
houps i have this error ;)
Platform error climate.climate_group - No module named 'homeassistnat'

**Comment by daenny** [comment]
oups.. typo :see_no_evil: try with "rc-3"

**Comment by sebaurel** [comment]
That works perfect !
Thank-you for your prompt response ;)

**Comment by daenny** [comment]
Does it work for you as expected? Then I will make a full release (non release candidate)

**Comment by sebaurel** [comment]
yes, I tested the activation and adjustment is it works well !
Thanks
